version: '3'

services:
    mailhog:
        container_name: mailhog
        image: mailhog/mailhog:v1.0.0
        ports:
          - "1025:1025"
          - "8025:8025"

    database:
        container_name: database
        image: 'mariadb:${MARIADB_TAG}'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
            MYSQL_DATABASE: ${DB_DBNAME} 
            MYSQL_USER: ${DB_USER} 
            MYSQL_PASSWORD: ${DB_PASSWORD} 
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '${DB_PORT}:3306'
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        container_name: php
        build:
            context: ./php
        ports:
            - '9000:9000'        
        volumes:
            - ./app:/var/www/app
        depends_on:
            - database

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8000:80'
            - '443:443'
        volumes:
            - ./app:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database


